### ISSUE TITLE
Blocklists and optional filtering

### ISSUE THREAD

**Issue by tina-hello** [futuredns/futuredns#1]
Please update the homepage to include what blocklists (and whitelists, if any) are used. I'm assuming you're recursive resolving directly from the VPS instead of using third party upstream, if so, state it as such.

Since you're using AdGuard Home, can you add optional filtering, eg, `security.dns.de.futuredns.eu.org` only block security threats (only enabling the AdGuard malware protection), `family.dns.de.futuredns.eu.org` add porn filtering (either from AdGuard family protection and/or using porn blocking upstream).

**Comment by futuredns** [comment]
We've updated our readme and website to include all the blocklists and whitelists we use, as well as the fact that we use Unbound on our own servers for recursive DNS resolving. Optional filtering is still on the todo list, but thanks for the feedback and helping us improve our service!
